//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootstrap v3.3.5 (http://getbootstrap.com)
        /// * Copyright 2011-2015 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// */
        ///.btn-default,
        ///.btn-primary,
        ///.btn-success,
        ///.btn-info,
        ///.btn-warning,
        ///.btn-danger {
        ///  text-shadow: 0 -1px 0 rgba(0, 0, 0, .2);
        ///  -webkit-box-shadow: inset 0 1px 0 rgba(255, 255, 255, .15), 0 1px 1px rgba(0, 0, 0, .075);
        ///          box-shadow: inset 0 1px 0 rgba(255, 255, 255, .15), 0 1px 1px rgba(0, 0, 0, .075);
        ///}
        ///.btn-default:active,
        ///.btn-prima [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BootstrapDashThemeDotCss {
            get {
                return ResourceManager.GetString("BootstrapDashThemeDotCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;version&quot;:3,&quot;sources&quot;:[&quot;bootstrap-theme.css&quot;,&quot;less/theme.less&quot;,&quot;less/mixins/vendor-prefixes.less&quot;,&quot;less/mixins/gradients.less&quot;,&quot;less/mixins/reset-filter.less&quot;],&quot;names&quot;:[],&quot;mappings&quot;:&quot;AAAA;;;;GAIG;ACeH;;;;;;EAME,yCAAA;EC2CA,4FAAA;EACQ,oFAAA;CFvDT;ACgBC;;;;;;;;;;;;ECsCA,yDAAA;EACQ,iDAAA;CFxCT;ACMC;;;;;;;;;;;;;;;;;;ECiCA,yBAAA;EACQ,iBAAA;CFnBT;AC/BD;;;;;;EAuBI,kBAAA;CDgBH;ACyBC;;EAEE,uBAAA;CDvBH;AC4BD;EErEI,yEAAA;EACA,oEAAA;EACA,8FAAA;EAAA,uEAAA;EAEA,uHAAA;ECnBF,oEAAA;EH4CA,4BAAA;EACA,sBAAA;EAuC2C,0BAAA;EAA2B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BootstrapDashThemeDotCssDotMap {
            get {
                return ResourceManager.GetString("BootstrapDashThemeDotCssDotMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootstrap v3.3.5 (http://getbootstrap.com)
        /// * Copyright 2011-2015 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// */.btn-danger,.btn-default,.btn-info,.btn-primary,.btn-success,.btn-warning{text-shadow:0 -1px 0 rgba(0,0,0,.2);-webkit-box-shadow:inset 0 1px 0 rgba(255,255,255,.15),0 1px 1px rgba(0,0,0,.075);box-shadow:inset 0 1px 0 rgba(255,255,255,.15),0 1px 1px rgba(0,0,0,.075)}.btn-danger.active,.btn-danger:active,.btn-default.active,.btn-default:active, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BootstrapDashThemeDotMinDotCss {
            get {
                return ResourceManager.GetString("BootstrapDashThemeDotMinDotCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootstrap v3.3.5 (http://getbootstrap.com)
        /// * Copyright 2011-2015 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// */
        ////*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */
        ///html {
        ///  font-family: sans-serif;
        ///  -webkit-text-size-adjust: 100%;
        ///      -ms-text-size-adjust: 100%;
        ///}
        ///body {
        ///  margin: 0;
        ///}
        ///article,
        ///aside,
        ///details,
        ///figcaption,
        ///figure,
        ///footer,
        ///header,
        ///hgroup,
        ///main,
        ///menu,
        ///nav,
        ///section,
        ///summary {
        ///  display: block;
        ///}
        ///audio,
        ///canvas,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BootstrapDotCss {
            get {
                return ResourceManager.GetString("BootstrapDotCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;version&quot;:3,&quot;sources&quot;:[&quot;bootstrap.css&quot;,&quot;less/normalize.less&quot;,&quot;less/print.less&quot;,&quot;less/glyphicons.less&quot;,&quot;less/scaffolding.less&quot;,&quot;less/mixins/vendor-prefixes.less&quot;,&quot;less/mixins/tab-focus.less&quot;,&quot;less/mixins/image.less&quot;,&quot;less/type.less&quot;,&quot;less/mixins/text-emphasis.less&quot;,&quot;less/mixins/background-variant.less&quot;,&quot;less/mixins/text-overflow.less&quot;,&quot;less/code.less&quot;,&quot;less/grid.less&quot;,&quot;less/mixins/grid.less&quot;,&quot;less/mixins/grid-framework.less&quot;,&quot;less/tables.less&quot;,&quot;less/mixins/table-row.less&quot;,&quot;less/forms.less&quot;,&quot;less/mixins/form [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BootstrapDotCssDotMap {
            get {
                return ResourceManager.GetString("BootstrapDotCssDotMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootstrap v3.3.5 (http://getbootstrap.com)
        /// * Copyright 2011-2015 Twitter, Inc.
        /// * Licensed under the MIT license
        /// */
        ///
        ///if (typeof jQuery === &apos;undefined&apos;) {
        ///  throw new Error(&apos;Bootstrap\&apos;s JavaScript requires jQuery&apos;)
        ///}
        ///
        ///+function ($) {
        ///  &apos;use strict&apos;;
        ///  var version = $.fn.jquery.split(&apos; &apos;)[0].split(&apos;.&apos;)
        ///  if ((version[0] &lt; 2 &amp;&amp; version[1] &lt; 9) || (version[0] == 1 &amp;&amp; version[1] == 9 &amp;&amp; version[2] &lt; 1)) {
        ///    throw new Error(&apos;Bootstrap\&apos;s JavaScript requires jQuery version 1.9.1 or higher&apos;)
        ///  }
        ///}(jQuer [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BootstrapDotJs {
            get {
                return ResourceManager.GetString("BootstrapDotJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootstrap v3.3.5 (http://getbootstrap.com)
        /// * Copyright 2011-2015 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%}body{margin:0}article,aside,details,figcaption,figure,footer,header,hgroup,main,menu,nav,section,summary{display:block}audio,canvas,progress,video{display:inline-block;vertical-align:b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BootstrapDotMinDotCss {
            get {
                return ResourceManager.GetString("BootstrapDotMinDotCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootstrap v3.3.5 (http://getbootstrap.com)
        /// * Copyright 2011-2015 Twitter, Inc.
        /// * Licensed under the MIT license
        /// */
        ///if(&quot;undefined&quot;==typeof jQuery)throw new Error(&quot;Bootstrap&apos;s JavaScript requires jQuery&quot;);+function(a){&quot;use strict&quot;;var b=a.fn.jquery.split(&quot; &quot;)[0].split(&quot;.&quot;);if(b[0]&lt;2&amp;&amp;b[1]&lt;9||1==b[0]&amp;&amp;9==b[1]&amp;&amp;b[2]&lt;1)throw new Error(&quot;Bootstrap&apos;s JavaScript requires jQuery version 1.9.1 or higher&quot;)}(jQuery),+function(a){&quot;use strict&quot;;function b(){var a=document.createElement(&quot;bootstrap&quot;),b={WebkitTrans [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BootstrapDotMinDotJs {
            get {
                return ResourceManager.GetString("BootstrapDotMinDotJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GlyphiconsDashHalflingsDashRegularDotEot {
            get {
                object obj = ResourceManager.GetObject("GlyphiconsDashHalflingsDashRegularDotEot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GlyphiconsDashHalflingsDashRegularDotSvg {
            get {
                object obj = ResourceManager.GetObject("GlyphiconsDashHalflingsDashRegularDotSvg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GlyphiconsDashHalflingsDashRegularDotTtf {
            get {
                object obj = ResourceManager.GetObject("GlyphiconsDashHalflingsDashRegularDotTtf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GlyphiconsDashHalflingsDashRegularDotWoff {
            get {
                object obj = ResourceManager.GetObject("GlyphiconsDashHalflingsDashRegularDotWoff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GlyphiconsDashHalflingsDashRegularDotWoff2 {
            get {
                object obj = ResourceManager.GetObject("GlyphiconsDashHalflingsDashRegularDotWoff2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery JavaScript Library v1.11.1
        /// * http://jquery.com/
        /// *
        /// * Includes Sizzle.js
        /// * http://sizzlejs.com/
        /// *
        /// * Copyright 2005, 2014 jQuery Foundation, Inc. and other contributors
        /// * Released under the MIT license
        /// * http://jquery.org/license
        /// *
        /// * Date: 2014-05-01T17:42Z
        /// */
        ///
        ///(function( global, factory ) {
        ///
        ///	if ( typeof module === &quot;object&quot; &amp;&amp; typeof module.exports === &quot;object&quot; ) {
        ///		// For CommonJS and CommonJS-like environments where a proper window is present,
        ///		// execute the factory and get jQuer [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JqueryDotJs {
            get {
                return ResourceManager.GetString("JqueryDotJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.
        ///require(&apos;../../js/transition.js&apos;)
        ///require(&apos;../../js/alert.js&apos;)
        ///require(&apos;../../js/button.js&apos;)
        ///require(&apos;../../js/carousel.js&apos;)
        ///require(&apos;../../js/collapse.js&apos;)
        ///require(&apos;../../js/dropdown.js&apos;)
        ///require(&apos;../../js/modal.js&apos;)
        ///require(&apos;../../js/tooltip.js&apos;)
        ///require(&apos;../../js/popover.js&apos;)
        ///require(&apos;../../js/scrollspy.js&apos;)
        ///require(&apos;../../js/tab.js&apos;)
        ///require(&apos;../../js/affix.js&apos;).
        /// </summary>
        internal static string NpmDotJs {
            get {
                return ResourceManager.GetString("NpmDotJs", resourceCulture);
            }
        }
    }
}
